### ISSUE TITLE
Job name length

### ISSUE THREAD

**Issue by jaimehrubiks** [ninech/relokator#1]
Thanks for this repository, it looks promising.

Here I leave you your first bug:

CRIT main.go:87 ▶ error running migration: Errors while migrating: [Errors while migrating: [Migration Error for PVC alertmanager-prometheus-operator-alertmanager-db-alertmanager-prometheus-operator-alertmanager-0 in namespace monitoring: error in phase migrateData: could not create migration job: could not create Job: Job.batch "relokator-alertmanager-prometheus-operator-alertmanager-db-alertmanager-prometheus-operator-alertmanager-0" is invalid: spec.template.labels: Invalid value: "relokator-alertmanager-prometheus-operator-alertmanager-db-alertmanager-prometheus-operator-alertmanager-0": must be no more than 63 characters]]

**Comment by tommyknows** [comment]
Hi @jaimehrubiks!

Thanks for reporting the issue. That's a really long name 😄 

I just submitted a PR, this should be fixed soon.
